# Generated by Django 6.0.4 on 2026-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(default='default_avatar.png', upload_to='images'),
        ),
    ]
