# Generated by Django 6.0.4 on 2026-04-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rarities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Sets',
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('energy_cost', models.IntegerField(default=0)),
                ('power_cost', models.IntegerField(default=0)),
                ('body', models.TextField(default='default')),
                ('variant', models.CharField(default='default', max_length=50)),
                ('domains', models.ManyToManyField(related_name='cards', to='cards.domain')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.rarity')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.set')),
                ('tags', models.ManyToManyField(related_name='cards', to='cards.tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.type')),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'ordering': ['card_number', 'name'],
                'indexes': [models.Index(fields=['card_number'], name='cards_card_card_nu_0f279e_idx'), models.Index(fields=['name'], name='cards_card_name_a125cc_idx'), models.Index(fields=['set'], name='cards_card_set_id_90fe6d_idx'), models.Index(fields=['rarity'], name='cards_card_rarity__8d0841_idx'), models.Index(fields=['type'], name='cards_card_type_id_d4edfc_idx')],
            },
        ),
    ]
