# Generated by Django 6.0.4 on 2026-04-24 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rarities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('set_id', models.CharField(max_length=10, unique=True)),
                ('tcgplayer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('card_count', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Sets',
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=50)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('supertype', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
                'ordering': ['type', 'supertype'],
                'unique_together': {('type', 'supertype')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('external_api_id', models.CharField(max_length=50, unique=True)),
                ('riftbound_id', models.CharField(max_length=20)),
                ('tcgplayer_id', models.CharField(max_length=20)),
                ('might', models.IntegerField(blank=True, null=True)),
                ('energy_cost', models.IntegerField(blank=True, null=True)),
                ('power_cost', models.IntegerField(blank=True, null=True)),
                ('body_text', models.TextField(default='default')),
                ('flavour_text', models.TextField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.CharField(default='default', max_length=50)),
                ('image_url', models.URLField(default='default', max_length=300)),
                ('domains', models.ManyToManyField(related_name='cards', to='cards.domain')),
                ('keywords', models.ManyToManyField(related_name='cards', to='cards.keyword')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.rarity')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.set')),
                ('tags', models.ManyToManyField(related_name='cards', to='cards.tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.type')),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'ordering': ['riftbound_id', 'name'],
                'indexes': [models.Index(fields=['name'], name='cards_card_name_a125cc_idx'), models.Index(fields=['might'], name='cards_card_might_5f7748_idx'), models.Index(fields=['energy_cost'], name='cards_card_energy__7fe7f7_idx'), models.Index(fields=['power_cost'], name='cards_card_power_c_be88bf_idx'), models.Index(fields=['type'], name='cards_card_type_id_d4edfc_idx'), models.Index(fields=['rarity'], name='cards_card_rarity__8d0841_idx'), models.Index(fields=['set'], name='cards_card_set_id_90fe6d_idx')],
            },
        ),
    ]
