# Generated by Django 6.0.4 on 2026-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['riftbound_id', 'name'], 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type', 'supertype'], 'verbose_name_plural': 'Types'},
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_card_nu_0f279e_idx',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='body',
            new_name='body_text',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='code',
            new_name='set_id',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='external_api_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='flavour_text',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='card',
            name='might',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='riftbound_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='tcgplayer_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='card_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='cardmarket_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='tcgplayer_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='supertype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('type', 'supertype')},
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['riftbound_id'], name='cards_card_riftbou_145999_idx'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
    ]
