# Generated by Django 6.0.4 on 2026-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'ordering': ['order'], 'verbose_name_plural': 'Rarities'},
        ),
        migrations.AddField(
            model_name='rarity',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
