# Generated by Django 6.0.4 on 2026-04-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_set_name_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='cardmarket_id',
        ),
    ]
