# Generated by Django 6.0.4 on 2026-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_set_cardmarket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='tcgplayer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
