# Generated by Django 6.0.4 on 2026-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='riftbound_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcgplayer_id',
            field=models.CharField(max_length=20),
        ),
    ]
