# Generated by Django 6.0.4 on 2026-04-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_riftbound_id_alter_card_tcgplayer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_riftbou_145999_idx',
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(related_name='cards', to='cards.keyword'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['might'], name='cards_card_might_5f7748_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['energy_cost'], name='cards_card_energy__7fe7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['power_cost'], name='cards_card_power_c_be88bf_idx'),
        ),
    ]
